def greet(name):
    print(f"Hello, {name}")
    greet(name)
    
greet("Alice")
greet("Bob")
greet("Charlie")
greet("David")
greet("Eve")
greet("Frank")
greet("Grace")
greet("Hannah")
greet("Ivy")
greet("Jack")
greet("Karen")
greet("Leo")
greet("Mona")
greet("Nina")
greet("Oscar")
greet("Paul")
greet("Quinn")
greet("Rachel")
greet("Sam")
greet("Tina")
                                 