import math
ans = math.sqrt(16)
print("The square root of 16 is:", ans)
print(math.pi)

print(math.e)

print(math.factorial(5))
print(math.log(10))
print(math.sin(math.pi/2))
print(math.cos(math.pi/2))
print(math.tan(math.pi/4))
print(math.degrees(math.pi/2))
print(math.radians(180))
print(math.ceil(4.2))
print(math.floor(4.8))
print(math.fabs(-4.8))
print(math.pow(2, 3))
print(math.isqrt(16))
print(math.gcd(48, 18))
print(math.lcm(12, 15))
print(math.dist([1, 2], [4, 6]))
print(math.hypot(3, 4))
print(math.erf(1))
print(math.erfc(1))
print(math.gamma(5))
print(math.lgamma(5))
print(math.ceil(4.2))
print(math.floor(4.8))
print(math.trunc(4.8))
print(math.exp(2))
print(math.log10(100))
print(math.log2(8))
print(math.sinh(1))
print(math.cosh(1))
print(math.tanh(1))
print(math.asinh(1))
print(math.acosh(1))
print(math.atanh(0.5))
print(math.acos(1))
print(math.asin(1))
print(math.atan(1))
print(math.hypot(5, 12))
print(math.isclose(0.1 + 0.2, 0.3))
print(math.isfinite(100))
print(math.isfinite(math.inf))
print(math.isfinite(math.nan))
print(math.isfinite(math.nan))